export const exampleResult = [
  {
    id: 631757,
    title:
      "Savory Slow Roasted Tomatoes with Filet of Anchovy and a zest of cum on top to make a bit more SPICY",
    image: "https://spoonacular.com/recipeImages/631757-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 1002044,
        amount: 1,
        unit: "small handful",
        unitLong: "small handful",
        unitShort: "small handful",
        aisle: "Produce;Spices and Seasonings",
        name: "herbs",
        original:
          "small handful of any fresh herbs you like, chopped - we use oregano but you can also use basil, thyme, etc.",
        originalName:
          "any fresh herbs you like, chopped - we use oregano but you can also use basil, thyme, etc",
        meta: ["fresh", "chopped", "canned"],
        extendedName: "canned fresh herbs",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/mixed-fresh-herbs.jpg",
      },
      {
        id: 15001,
        amount: 8,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Seafood",
        name: "anchovy filets",
        original:
          "8 high quality anchovy filets, (we use anchovies from Sardegna packed in salt)",
        originalName:
          "high quality anchovy filets, (we use anchovies from Sardegna packed in salt)",
        meta: ["packed in salt)"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/anchovies.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 11529,
        amount: 4,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "tomatoes",
        original: "4 round tomatoes (we grow & use grappolo for this dish)",
        originalName: "round tomatoes (we grow & use grappolo for this dish)",
        meta: ["for this dish)"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/tomato.png",
      },
    ],
    unusedIngredients: [],
    likes: 10,
  },
  {
    id: 638288,
    title: "Chicken Roll-Ups With Feta Cheese and Arugula",
    image: "https://spoonacular.com/recipeImages/638288-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 5062,
        amount: 1.5,
        unit: "pounds",
        unitLong: "pounds",
        unitShort: "lb",
        aisle: "Meat",
        name: "chicken breast cutlets",
        original: "8 chicken breast cutlets, (about 1 ½ pounds)",
        originalName: "chicken breast cutlets, (about",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/chicken-breasts.png",
      },
      {
        id: 10011959,
        amount: 1,
        unit: "bunch",
        unitLong: "bunch",
        unitShort: "bunch",
        aisle: "Produce",
        name: "baby arugula",
        original: "1 bunch large baby arugula",
        originalName: "baby arugula",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/arugula-or-rocket-salad.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 11955,
        amount: 3,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Canned and Jarred;Produce",
        name: "feta cheese",
        original:
          "3 ounces soft crumbled feta cheese with basil and sun-dried tomato, broken into small pie",
        originalName:
          "soft crumbled feta cheese with basil and sun-dried tomato, broken into small pie",
        meta: [
          "with basil and sun-dried tomato, broken into small pie",
          "crumbled",
          "soft",
        ],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/sundried-tomatoes.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 2,
  },
  {
    id: 645555,
    title: "Green Tomato Salad",
    image: "https://spoonacular.com/recipeImages/645555-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 10211111,
        amount: 1,
        unit: "teaspoon",
        unitLong: "teaspoon",
        unitShort: "tsp",
        aisle: "Ethnic Foods;Spices and Seasonings",
        name: "sumac",
        original: "1 teaspoon of sumac powder",
        originalName: "sumac powder",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/dried-sumac.jpg",
      },
      {
        id: 2064,
        amount: 1,
        unit: "handful",
        unitLong: "handful",
        unitShort: "handful",
        aisle: "Produce;Spices and Seasonings",
        name: "mint leaves",
        original: "A handful of sage and mint leaves, finely chopped",
        originalName: "A of sage and mint leaves, finely chopped",
        meta: ["finely chopped"],
        extendedName: "fresh mint leaves",
        image: "https://spoonacular.com/cdn/ingredients_100x100/mint.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 11527,
        amount: 1,
        unit: "large",
        unitLong: "large",
        unitShort: "large",
        aisle: "Produce",
        name: "green tomato",
        original: "1 large green tomato",
        originalName: "green tomato",
        meta: ["green"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/green-tomato.png",
      },
    ],
    unusedIngredients: [],
    likes: 1,
  },
  {
    id: 769775,
    title: "Simple Spinach and Tomato Frittata",
    image: "https://spoonacular.com/recipeImages/769775-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 3,
    missedIngredients: [
      {
        id: 99037,
        amount: 1,
        unit: "small",
        unitLong: "small",
        unitShort: "small",
        aisle: "Pasta and Rice",
        name: "personal skillet",
        original: "small personal skillet",
        originalName: "personal skillet",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/no.jpg",
      },
      {
        id: 1123,
        amount: 2,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "2-3 lightly beaten eggs",
        originalName: "lightly beaten eggs",
        meta: ["lightly beaten"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/egg.png",
      },
      {
        id: 10011457,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "spinach leaves",
        original: "spinach leaves",
        originalName: "spinach leaves",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/spinach.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 10311529,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "cherry tomatoes",
        original: "cherry tomatoes, halved",
        originalName: "cherry tomatoes, halved",
        meta: ["halved"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/cherry-tomatoes.png",
      },
    ],
    unusedIngredients: [],
    likes: 7,
  },
];
